# Generated by Django 5.1.1 on 2024-09-28 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='bidsList', to=settings.AUTH_USER_MODEL),
        ),
    ]
