# Generated by Django 5.1.1 on 2024-09-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userBid', to='auctions.bid'),
        ),
    ]
