# Generated by Django 4.2.16 on 2024-10-12 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_initial_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creating_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
