# Generated by Django 4.2.16 on 2024-10-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
